name: Update Nginx Proxy Manager

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行
  workflow_dispatch: # 手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "liuyie"  # 替换为你的 GitHub 用户名
        git config user.email "314673846@qq.com"  # 替换为你的 GitHub 邮箱

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/NginxProxyManager/nginx-proxy-manager.git
        git fetch upstream

    - name: Merge upstream develop branch into the fork
      run: |
        git checkout develop  # 切换到你的仓库中的 develop 分支
        git merge upstream/develop --allow-unrelated-histories  # 强制合并不同历史的分支, 合并上游仓库的 develop 分支

    - name: Push changes to the fork
      run: |
        git push origin develop  # 将合并的更改推送到你的仓库
